services:
  dns-switcher:
    container_name: dns-switcher-server
    image: ghcr.io/misshanya/dns-switcher
    ports:
      - "53:53"
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped
